

---
title: Week 8 - Nonlinear Regression
sitetitle: Week 8
summary: "EC200 - Week 8 Hypothesis Testing with Multiple Regression (CH8)"

date: "2021-10-11"
start_date: "2021-10-18"
end_date: "2021-10-25"

  
  # Academic page type (do not modify).
type: docs
menu:
  content:
    parent: Course content
    weight: 8
    
output:
  blogdown::html_page:
    toc: true

pdf: /slides/ch8-slides.pdf
thumb: /slides/ch8-slides.png



---

## Overview

Let's make regressions faaaancy, with three new friends: **polynomials**, **logarithms**, and **interactions**! 

## Reading Guide

#### **Chapter 8: Nonlinear Regression Functions**

#### **SW 8.1** A General Strategy for Modeling Nonlinear Regression Functons

Key takeaway here - thnk about the economic theory and its application to determine the best approach to modeling! 


#### **SW 8.2** Nonlinear Functions of a Single Independent Variable 

Polynomials and logs. Note that this section includes only 3 ways of setting up equations: level-level, log-log, log-level. We'll also cover level-log, because, why not?

#### **SW 8.3** Interactions Between Independent Variables

Three types of interactions you should know: 

1. Binary-binary
2. Continuous-binary
3. Contnuous-continuous



## Slides

`r blogdown::shortcode("slides")`

## Videos

*Warning!* The interactions example I work through is ... uninspired. I clearly should not have taken on baseball. I regret it. :flushed: :grimacing: Also, the reason why there are only 3 race/ethnicity categories in the MLB is because in 1993, all players fell into only those three groups!

### [Video: Nonlinear Reression Functions](https://youtu.be/LAPKh9ib2Tg )
`r htmltools::HTML("{{< youtube LAPKh9ib2Tg >}}")`


