---
title: "MS Teams Resources"
sitetitle: MS Teams
summary: MS Teams etiquette and resources
date: "2022-08-20"

menu:
  resources:
    parent: Resources
    weight: 3
  
  # Academic page type (do not modify).
type: docs
output:
  blogdown::html_page:
    toc: true
---

## EC200 Norms for Teams 

We’re a small(ish) class, which means we can a little flexible on norms. Also, as we learn what works best, we may favor some methods of collaborating over others.  


Monday and Wednesday will be synchronous classes. We will meet on Teams. You will receive an invite in your e-mail. 
 

### Recording	
I plan to record Monday and Wednesday sessions and make them available on Teams. 

### Cameras 	
We will feel more like humans if we can see each other. I encourage you to keep your camera on during class sessions, but it is not required. Of course, if you need to use the bathroom, grab a snack, wrangle a cat – feel free to shut it off briefly. If you don’t want to feel like we’re all hanging out in your bedroom, feel free to [change/blur]( https://support.microsoft.com/en-us/office/change-your-background-for-a-teams-meeting-f77a2381-443a-499d-825e-509a140f4780) your background. If you are not comfortable with your camera on, I’d appreciate it if you’d load up picture or avatar.  

### Chat/hand 	
During lectures/demonstrations, please feel free to use the chat as a place to ask questions, or raise your hand. I will also ask questions of you, and the best way to respond is with the chat or hand, depending on your preference. 


### Microphone
In general, please keep your microphone muted unless you are speaking. 



### What if you have technical problems?  
Don’t worry, just do your best to get back online. If it’s a total loss, you can catch up w/ the recordings afterward. 

### What if _I_ have technical problems? 
My internet is usually okay, but sometimes my computer gets overexcited and just cannot cope. If I drop out, just wait and I’ll rejoin as quickly as I can. 
If for some reason Teams crashes/explodes, we’ll switch to Zoom. I’ll post a permanent link on Teams to our “back-up” location.   
If for some reason all is truly lost, I’ll send an announcement, we’ll end class early and resume in our next session .  

## Rusty on Teams? 

ETS has a good [overview](https://www.uvm.edu/it/kb/article/teams/) of the basics behind MS Teams, with a specific focus on [how students are likely to use it]( https://www.uvm.edu/it/kb/article/class-teams-for-students/)

- [Change your background on Teams]( https://support.microsoft.com/en-us/office/change-your-background-for-a-teams-meeting-f77a2381-443a-499d-825e-509a140f4780)

- [Change your photo/avatar]( https://support.microsoft.com/en-us/office/change-your-picture-in-teams-7a711943-9248-420e-b814-c071aa8d9b9c) 


