---
title: "Research paper checklist"
sitetitle: Checklist
summary: Research paper checklist
date: "2020-08-20"

menu:
  resources:
    parent: Research paper
    weight: 4
    
type: docs
---
*Guidelines and tips for papers**

-   Active voice

-   First-person singular/plural (as appropriate)

-   Paper divided numbered, labeled sections.

-   No personal opinions

-   Present tense

**Abstract & Title**

-   Descriptive title included

-   200 words or less abstract

**Introduction**

-   States your research question clearly

-   Explains what economic theory says about the potential answers to
    your questions, and/or defines clear hypotheses that you test

-   Describes why your topic is important

-   Describes what you do

-   Describes what you find

-   Describe how it contributes

-   Reader can infer all main points of paper just from introduction

**Motivation/Literature Review**

-   Includes papers that have answered your research question (or
    similar research question)

-   Research results described in present tense ("Smith finds," not
    "Smith found")

-   Papers linked clearly to their contribution (as relates to your
    research question)

    -   For example,

**Methodology/Data**

-   Data source described and cited

-   Population model written out

    -   Use proper equation notation (betas, u, etc)

    -   Use appropriate subscripts (*i, t, y, etc)*

    -   All relevant variables explained/defined

    -   Use "real names" to describe variables when possible (ie use
        *female* for women, not *w1*)

-   Describe your methodology. Are you estimating a model using OLS? If
    so, say so.

-   Correct standard errors: robust? Clustered? Something else?

**Results**

-   When using categorical/dummy variables, what is your omitted
    category? Make sure you know and that it's clear.

-   What are the units of your measures?

    -   Is that percent or percentage points?

-   In most contexts, about 3 places past the decimal point is right,
    but it depends on the magnitudes. If you really want to be precise,
    set and stick to a reasonable number of significant digits. There's
    no place for a number like 0.05403823 or 0.0000000 in your tables.

**Tables and Figures**

-   Tables should be properly formatted. That is, they should be made in
    Excel (or LaTeX) and NEVER copied and pasted out of Stata

-   Variables should be described using real words. Ie, "number of
    children," not "numchld."

-   Tables and figures should be numbered (Table 1, Table 2, etc...
    Figure 1, Figure 2, etc.) and should also be given a title. Refer to
    tables by their numbers in the text.

-   

**References**

-   Use footnotes rather than endnotes

-   At the end of your paper, include list of references cited

-   You can format using APA, MLA, or Chicago style

    -   Citation Owl or Google Scholar will do it for you

-   In-text, cite with author and year (Author, Year; Author, Year) or
    (Author Year, Author Year)

**Working with data**

If you're working with people

-   What is the age range you want in your sample?

-   What years of data do you need?

-   If in the US, do you want citizens, or do you also want to include
    immigrants?

-   If dealing with labor force variables, do you want all people of
    working age, all those who are in the labor force, or all who are
    employed?

**[\
]{.ul}**

**[Checklist for papers:]{.ul}**

**General**

-   First-person active voice! (I estimate a regression, **NOT** "A
    regression is estimated")

    -   Single-authored paper first person singular, "I." (You're not
        the queen!)

    -   Joint-authored paper first person plural, "we."

    -   Don't believe me? Check out any economics paper published in the
        past 20 years. There's *some* variation in I vs. we, but *all*
        use active voice.

-   Paper divided numbered, labeled sections.

-   At the back of your mind, when motivating your paper, ask "what is
    the link to economics"?

    -   If studying discrimination, what does economic theory tell us
        about why discrimination exists/persists

    -   If studying stock market returns, what do economic models tell
        us about our ability to predict returns?

-   A research paper is not an essay!

    -   Personal opinions don't have a place

    -   Sources should be primarily academic (peer-reviewed journals,
        working papers, etc.), maybe some non-academic sources for
        motivation only

    -   Clear, labeled sections

**Abstract & Title**

-   Include a title

-   Abstract should be 200 words or less and serve as summary of paper,
    including motivation, empirical strategy, findings.

**Introduction**

-   Introduction reads like an academic article. Motivates, describes
    what you do and what you find. (Almost like a mini-paper!)

-   

**Methodology/Data**

-   Describe the data you use, where did it come from? If you didn't
    create it, cite it

-   Write out the population model you estimate. If you're using Word,
    use equation editor. Make it look nice. Don't forget the error term

-   Describe your methodology. Are you estimating a model using OLS? If
    so, say so.

-   Correct standard errors: robust? Clustered? Something else?

**Results**

-   When using categorical/dummy variables, what is your omitted
    category? Make sure you know and that it's clear.

-   What are the units of your measures?

    -   Is that percent or percentage points?

-   In most contexts, about 3 places past the decimal point is right,
    but it depends on the magnitudes. If you really want to be precise,
    set and stick to a reasonable number of significant digits. There's
    no place for a number like 0.05403823 or 0.0000000 in your tables.

**Tables and Figures**

-   Tables should be properly formatted. That is, they should be made in
    Excel or LaTeX, and NEVER copied and pasted out of Stata

-   Variables should be described using real words. Ie, "number of
    children," not "numchld."

-   Tables and figures should be numbered (Table 1, Table 2, etc...
    Figure 1, Figure 2, etc.) and should also be given a title. Refer to
    tables by their numbers in the text.

-   

**References**

-   At the end of your paper, include list of references cited

-   You can format using APA, MLA, or Chicago style

    -   Citation Owl?

    -   Google Scholar will do it for you

-   In-text, cite with author and year (Author, Year; Author, Year) or
    (Author Year, Author Year)
